package gg.playit.minecraft;

import gg.playit.api.model.request.AgentVersion;

/** Generated by build - version is injected from build.gradle. */
public final class PlayitConstants {
    private PlayitConstants() {}

    public static final AgentVersion MINECRAFT_AGENT_VERSION =
            new AgentVersion("f4e73f52-f35c-4f18-9ab2-3aaa5c4488c1", 0, 2, 0);

    /** Version string for ReqClaimSetup (e.g. "0.2.0") */
    public static final String VERSION_STRING = "0.2.0";
}
